### PR TITLE
ASMT 3143 - Apply all upstream Excalidraw commits since November 2023  

### PR DESCRIPTION
**Pull request by manny-douge**
Sister hyperpad [PR](https://github.com/Karat/hyperpad/pull/828) 

When we forked Excalidraw, there was a bug with the undo/redo functionality. An upstream fix was [merged](https://github.com/excalidraw/excalidraw/pull/7348) in April but we had already made quite a few changes since then. 

The approach I took to update this PR was:

Pull down latest excalidraw (rather than the April version), figure out what each of the 33 commits we're trying to do on the `karat` branch, then apply a new set of changes to the new upstream. I then removed the new `AI` tag on the more tools button, the all the socials in the hamburger icon and modified how the packaging worked since the Excalidraw repo moved to workspaces && dropped webpack. 

I didn't do a traditional CLI based rebase because the fast forward was making changes that made it difficult to track where things went (e.g) `index.tsx` was gutted and moved to `App.tsx` (fast forward was removing all changes from App.tsx since there were no conflicts) even though it was the new home for the code. 

That being said, it looks we got a new toolbar on the side + undo/redo works properly now.

I have no idea how to make this PR easier to review 😅 .

[IV room ](https://karatstudio.cotrain.io/collab/8ecb59c7db0801401d7673f8ef8e0ae07fce51392195cb3f9e82d668a91811ab)
[Complete interview result here with PNG of whiteboard activity](https://central.cotrain.io/assessments/221216988)

Screenshot 2024-10-10 at 1 44 16 PM
Screenshot 2024-10-10 at 2 00 06 PM

Video testing release of `0.0.27-alpha-38` on hyperpad staging.

https://github.com/user-attachments/assets/0e14f128-bf65-484d-96b8-c3776a94f76e

Screenshot 2024-10-10 at 2 07 28 PM

### CODE REVIEW

**Comment by ericd-karat** [comment]
[here](https://github.com/Karat/excalidraw/compare/a977dd1bf53091830062071889ebf3542d85a772...ASMT-3143#diff-2f8466e3b5377dceefcd656421fbfd29f5446c0daf4127f3882d8f6ce58e0588R59) might be good to have a comment on what useI18n is.

**Comment by ericd-karat** [comment]
[here](https://github.com/Karat/excalidraw/compare/a977dd1bf53091830062071889ebf3542d85a772...ASMT-3143#diff-2f8466e3b5377dceefcd656421fbfd29f5446c0daf4127f3882d8f6ce58e0588R93) either dont catch the error or do something with it

**Comment by ericd-karat** [comment]
[here](https://github.com/Karat/excalidraw/compare/a977dd1bf53091830062071889ebf3542d85a772...ASMT-3143#diff-5dee2701b4037c4be0d550937e902122511c3dc98f8fe4a66f68fa0df01c9421R32) Not really sure whats going on with deleted/commented out code

**Comment by ericd-karat** [comment]
It looks generally okay but did you intend to leave all that commented-out code in there or not?  Might be good to delete it if it's not necessarily to understand something else.

**Review by ericd-karat — APPROVED** [review]
Clean up the commented-out code if you get a chance.  Otherwise looks good from what I can tell.  I would suggest a thorough smoke test.

**Comment by manny-douge** [comment]
> [here](https://github.com/Karat/excalidraw/compare/a977dd1bf53091830062071889ebf3542d85a772...ASMT-3143#diff-2f8466e3b5377dceefcd656421fbfd29f5446c0daf4127f3882d8f6ce58e0588R59) might be good to have a comment on what useI18n is.

Oh yeah this is where it didn't split the changes well, I didn't add `uesi18n`, it is from from the upstream changes. 



> [here](https://github.com/Karat/excalidraw/compare/a977dd1bf53091830062071889ebf3542d85a772...ASMT-3143#diff-2f8466e3b5377dceefcd656421fbfd29f5446c0daf4127f3882d8f6ce58e0588R93) either dont catch the error or do something with it

If this link is referring to the `window.alert(t("alerts.decryptFailed"));` line,  this is also an artifact from my changes, I will remove it.

> It looks generally okay but did you intend to leave all that commented-out code in there or not? Might be good to delete it if it's not necessarily to understand something else.

Yeah, the commented out stuff was for the browser build which I removed, I figured we might need it in the future but keeping it in looks messy, I'll remove it!

**Pull request merged**
